blank_issues_enabled: true
contact_links:
  - name: A question, an idea, or anything open-ended
    url: https://github.com/IndyWH/OpenConsult/discussions
    about: Discussions are the better place for these.
